export default [
    {
        description: "Coca cola: red can",
        img: "",
        _id: "5bbdfsadsa",
        productType: "drink",
        name: "Demo: Classic Cola",
        costPrice: 0.3,
        retailPrice: 3,
        quantity: 10000,
        supplierName: "Cola inc.",
        supplierPhone: "2234566787567",
        supplierAddress: "the moon, 3rd crater to the left",
    },
    {
        description: "Coca cola: black can",
        img: "",
        _id: "5bbdf5f5df5f5f5f",
        productType: "drink",
        name: "Demo: Cola Zero",
        costPrice: 0.3,
        retailPrice: 3,
        quantity: 18,
        supplierName: "Cola inc.",
        supplierPhone: "2234566787567",
        supplierAddress: "the moon, 3rd crater to the left",
    },
    {
        description: "Spicy corn chips",
        img: "",
        _id: "5bbdfsads5656565656565",
        productType: "snack",
        name: "Demo: Doritos",
        costPrice: 5,
        retailPrice: 10,
        quantity: 50,
        supplierName: "the Doritos company",
        supplierPhone: "2234566787567",
        supplierAddress: "Jupiter",
    },
]